import { defaultApiParams } from '../../config/serviceConfig.js';

export function buildRetrieveSaleProductRequestBody({
  saleProductCode,
  reservationCode,
  startDate,
  endDate,
  productAttributeCode,
  productAreaCode,
  saleProductName,
  brandCd,
  pageSize,
  pageNumber,
  totalRowCount,
  totalPageCount,
}) {
  return {
    productCodeDivision: "P",
    productCode: saleProductCode || "",
    productSeparator: "",
    reservationCode: reservationCode || "",
    productAreaCode: productAreaCode || "AA",
    teamDivisionCode: "",
    arrangementEmployeeNumber: "",
    merchandiserEmployeeNumber: "",
    airEmployeeNumber: "",
    directPurchaseHotelEmployeeNumber: "",
    departureArrivalDivisionCode: "S",
    startDate: startDate,
    endDate: endDate,
    productBrowseTypeCode: "",
    productTypeCode: "",
    transitTypeCode: "",
    allYn: "A",
    sundayYn: "",
    mondayYn: "",
    tuesdayYn: "",
    wednesdayYn: "",
    thursdayYn: "",
    fridayYn: "",
    saturdayYn: "",
    productBrandCode: brandCd || "",
    promotionCode: "",
    productDivisionCode: "",
    themeCode: "",
    inventoryPatternId: "",
    departureAirCode: "",
    departureFlightCode: "",
    arrivalAirCode: "",
    arrivalFlightCode: "",
    departureCityCode: "",
    teamDepartmentCode: "",
    saleProductName: saleProductName || "",
    hotelCode: "",
    landCode: "",
    adultAmount: "",
    basisFeeRate: null,
    officialCertificationFeeRate: null,
    affiliatedConcernFeeRate: null,
    depositKindCode: "",
    productAttributeCode: productAttributeCode || "",
    tempArngNm: "",
    tempMrchNm: "",
    tempAirNm: "",
    tempDpurcNm: "",
    tempCard: "",
    productAreaExceptCode: "G",
    stateCodeInformation: "",
    cityCodeInformation: "",
    specificAgentCode: "",
    supplierHeadOfficeDispatchExistenceOrNonexistence: "N",
    pageVo: {
      pageSize: pageSize || 100,
      pageNumber: pageNumber || 1,
      totalRowCount: totalRowCount || 0,
      totalPageCount: totalPageCount || 0,
    },
    header: {
      langCode: defaultApiParams.commonCodeLang,
    },
  };
}
